name: base                                                                   
channels:                                                                    
  - defaults                                                                 
dependencies:                                                                
  - pandas
  - jupyterlab
  - matplotlib
